
import random
from hashlib import sha256

def _sha256(text) -> str:
    return sha256(text.encode()).hexdigest()


def _get_random_id() -> str:
    """
    Generates a random ID.
    Atom's ID is generated by this function.

    @return str: A SHA-256 hash string representing the random ID.
    """
    # Convert the random float to a string before hashing
    return _sha256(str(random.random()))[:25]

def _get_hash_id(content: str | bytes) -> str:
    """
    Generates a hash ID from the given text/binary.
    Quark's ID is generated by this function.

    @param content str|bytes: The content to be hashed.
    """
    if isinstance(content, str):
        return _sha256(content)
    return sha256(content).hexdigest()